// <auto-generated />
namespace Travel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Zmianawtrasie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Zmianawtrasie));
        
        string IMigrationMetadata.Id
        {
            get { return "201712021243405_Zmiana w trasie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
